CREATE TABLE "custom_field_definitions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	"label" varchar(200) NOT NULL,
	"field_type" varchar(20) NOT NULL,
	"options" jsonb,
	"required" integer DEFAULT 0,
	"order_index" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "military_personnel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "military_personnel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ord" integer,
	"posto_graduacao" varchar(50) NOT NULL,
	"arma_quadro_servico" varchar(50),
	"nome_completo" varchar(200) NOT NULL,
	"nome_guerra" varchar(100),
	"companhia" varchar(50) NOT NULL,
	"secao_fracao" varchar(100),
	"funcao" varchar(100),
	"data_praca" varchar(50),
	"curso" varchar(100),
	"situacao" varchar(50),
	"missao_op" varchar(100),
	"cpf" varchar(14),
	"identidade" varchar(50),
	"endereco" text,
	"numero_residencia" varchar(20),
	"bairro" varchar(100),
	"ponto_referencia" varchar(200),
	"cidade" varchar(100),
	"telefone_contato_1" varchar(20),
	"telefone_contato_2" varchar(20),
	"email" varchar(200),
	"observacoes" text,
	"custom_fields" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "saved_filter_groups" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(200) NOT NULL,
	"description" text,
	"owner_id" varchar NOT NULL,
	"scope" varchar(20) DEFAULT 'personal' NOT NULL,
	"filter_tree" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_preferences" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"preference_key" varchar(100) NOT NULL,
	"preference_value" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"nome_guerra" varchar(100),
	"posto_graduacao" varchar(50),
	"profile_image_url" varchar,
	"role" varchar(20) DEFAULT 'user' NOT NULL,
	"permissions" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "saved_filter_groups" ADD CONSTRAINT "saved_filter_groups_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_preferences" ADD CONSTRAINT "user_preferences_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");--> statement-breakpoint
CREATE INDEX "IDX_user_preferences_userId" ON "user_preferences" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "IDX_user_preferences_key" ON "user_preferences" USING btree ("user_id","preference_key");